name: Terraform web-servers

on:
  push:
    branches:
      - main

permissions:
  id-token: write   # Required for OIDC
  contents: read    # Required to clone the repo
            
jobs:
  terraform:
    runs-on: ubuntu-latest 

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::111225938018:role/github-oidc-auth
          aws-region: us-east-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.5.0

      - name: Terraform Init
        id: init
        run: terraform init

      # - name: Terraform Format
      #   id: fmt
      #   run: terraform fmt -check

      - name: Terraform Validate
        id: validate
        run: terraform validate

      - name: Terraform Plan
        id: plan
        # if: github.event_name == 'pull_request'
        run: terraform plan -no-color
        # env:
          # GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Required for commenting on PRs

      - name: Terraform Apply
        id: apply
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: terraform apply -auto-approve

      # - name: Terraform destroy
      #   id: destroy
      #   if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      #   run: terraform destroy -auto-approve
